### ISSUE TITLE
[TODO] Add an express server 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/AgiliZenti#2]
This app is a Full Stack JavaScript app with MongoDB, Express, React and Node. This is a client and server project.

Create React App includes a development server.

This app needs a Express and Node server.

I don't know if I did this correctly but this could possibly create a separate server folder and a server.js file. This could possibly have another package.json from doing an npm init inside the server folder.

**Comment by soroush-habibi** [comment]
Hi
If you need a separate API server with express i can make it for you.Is that what you mean?

**Comment by gbowne1** [comment]
Yes @soroush-habibi that is what I meant.

**Comment by soroush-habibi** [comment]
Is it ok to use Prisma ORM for connecting to mongodb?

**Comment by gbowne1** [comment]
Yes it is.  I planned on using Prisma.  @soroush-habibi 

Sorry for the confusion if any
